version: '2'

services:
  master:
    build: ./hadoop-master
    ports:
      - "50070:50070"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
    container_name: "master"
  slave1:
    build: ./hadoop-slave
    container_name: "slave1"
  slave2:
    build: ./hadoop-slave
    container_name: "slave2"
  slave3:
    build: ./hadoop-slave
    container_name: "slave3"
